-- Sample data for trying free-clay. Every company, person and domain here is fictional, and every
-- domain is under example.com, which is reserved for examples (RFC 2606), so a run against these
-- rows can never reach a real business. Safe to run more than once: it skips if the table exists.
--   npx wrangler d1 execute free-clay --local --file seed.sql
-- json_each rather than UNION ALL: D1 caps how many terms a compound SELECT may have.

INSERT INTO tables (name, position, created_at, updated_at)
  SELECT 'Sample: Florida roofers', 0, '2026-09-27T12:00:00.000Z', '2026-09-27T12:00:00.000Z'
  WHERE NOT EXISTS (SELECT 1 FROM tables WHERE name = 'Sample: Florida roofers' AND deleted_at IS NULL);

-- Five data columns, a formula, two free enrichments, a waterfall and an AI column (not run: it needs a key).
INSERT INTO columns (table_id, key, name, kind, type, config, position, created_at)
  SELECT t.id, json_extract(c.value, '$.key'), json_extract(c.value, '$.name'), json_extract(c.value, '$.kind'),
         json_extract(c.value, '$.type'), json_extract(c.value, '$.config'), json_extract(c.value, '$.pos'), '2026-09-27T12:00:00.000Z'
  FROM (SELECT id FROM tables WHERE name = 'Sample: Florida roofers' AND deleted_at IS NULL) t, json_each('[{"key": "company", "name": "Company", "kind": "data", "type": "text", "config": {}, "pos": 0}, {"key": "website", "name": "Website", "kind": "data", "type": "url", "config": {}, "pos": 1}, {"key": "first_name", "name": "First name", "kind": "data", "type": "text", "config": {}, "pos": 2}, {"key": "last_name", "name": "Last name", "kind": "data", "type": "text", "config": {}, "pos": 3}, {"key": "city", "name": "City", "kind": "data", "type": "text", "config": {}, "pos": 4}, {"key": "domain", "name": "Domain", "kind": "formula", "type": "text", "config": {"formula": "DOMAIN({{website}})"}, "pos": 5}, {"key": "email_provider", "name": "Email provider", "kind": "enrich", "type": "text", "config": {"fn": "email_provider", "inputs": {"domain": "{{domain}}"}, "outputs": [], "condition": "", "auto": false}, "pos": 6}, {"key": "site_status", "name": "Site status", "kind": "enrich", "type": "select", "config": {"fn": "website_check", "inputs": {"domain": "{{domain}}"}, "outputs": [], "condition": "", "auto": false}, "pos": 7}, {"key": "work_email", "name": "Work email", "kind": "waterfall", "type": "email", "config": {"steps": [{"fn": "find_contact_info", "inputs": {"domain": "{{domain}}"}, "enabled": true}, {"fn": "hunter_email_finder", "inputs": {"first_name": "{{first_name}}", "last_name": "{{last_name}}", "domain": "{{domain}}"}, "enabled": false}, {"fn": "email_permutations", "inputs": {"first_name": "{{first_name}}", "last_name": "{{last_name}}", "domain": "{{domain}}"}, "enabled": true}], "validate": {"fn": "email_check", "pass": "valid"}, "provider_column": null, "outputs": [], "condition": "NOT(ISBLANK({{domain}}))", "auto": false}, "pos": 8}, {"key": "residential", "name": "Does residential?", "kind": "ai", "type": "checkbox", "config": {"provider": "groq", "model": "qwen/qwen3.8-27b", "prompt": "Does {{company}} ({{website}}) do residential roofing? Answer from the name only if you must.", "system": "", "fields": [{"name": "residential", "type": "checkbox"}], "outputs": [], "max_tokens": 256, "est_input_tokens": 120, "condition": "", "auto": false}, "pos": 9}]') c
  WHERE NOT EXISTS (SELECT 1 FROM columns WHERE table_id = t.id);

INSERT INTO rows (table_id, data, created_at, updated_at)
  SELECT t.id, r.value, '2026-09-27T12:00:00.000Z', '2026-09-27T12:00:00.000Z'
  FROM (SELECT id FROM tables WHERE name = 'Sample: Florida roofers' AND deleted_at IS NULL) t, json_each('[{"company": "Gator Ridge Roofing", "website": "https://www.gatorridge.example.com", "first_name": "Dana", "last_name": "Whitfield", "city": "Gainesville", "email_provider": "Google Workspace", "site_status": "live", "work_email": "office@gatorridge.example.com"}, {"company": "Suncoast Shingle Co", "website": "suncoastshingle.example.com", "first_name": "Marco", "last_name": "Reyes", "city": "Tampa", "email_provider": "Microsoft 365", "site_status": "live", "work_email": "marco.reyes@suncoastshingle.example.com"}, {"company": "Palmetto Peak Roofs", "website": "palmettopeak.example.com", "first_name": "Leah", "last_name": "Okafor", "city": "Orlando", "email_provider": "Other", "site_status": "parked"}, {"company": "Keystone Coastal Roofing", "website": "keystonecoastal.example.com", "first_name": "Sam", "last_name": "Duarte", "city": "Jacksonville"}, {"company": "Blue Heron Roof Repair", "website": "blueheron.example.com", "first_name": "Priya", "last_name": "Nair", "city": "Ocala"}, {"company": "Tri-County Roof Pros", "first_name": "Owen", "last_name": "Baptiste", "city": "Lakeland"}, {"company": "Coquina Roofing & Gutters", "website": "https://coquina.example.com/contact", "first_name": "Rosa", "last_name": "Lindqvist", "city": "St. Augustine"}, {"company": "Seminole State Roofing", "website": "seminolestate.example.com", "city": "Sanford"}]') r
  WHERE NOT EXISTS (SELECT 1 FROM rows WHERE table_id = t.id);

-- A few cell statuses, so the grid shows done, no result and error before anything has run.
INSERT OR IGNORE INTO cells_meta (row_id, column_id, status, provider, cost_micros, error, updated_at)
  SELECT r.id, c.id, json_extract(m.value, '$.status'), json_extract(m.value, '$.provider'), 0, json_extract(m.value, '$.error'), '2026-09-27T12:00:00.000Z'
  FROM (SELECT id FROM tables WHERE name = 'Sample: Florida roofers' AND deleted_at IS NULL) t
  JOIN rows r ON r.table_id = t.id
  JOIN columns c ON c.table_id = t.id
  JOIN json_each('[{"company": "Gator Ridge Roofing", "col": "email_provider", "status": "done", "provider": "email_provider", "error": null}, {"company": "Gator Ridge Roofing", "col": "site_status", "status": "done", "provider": "website_check", "error": null}, {"company": "Gator Ridge Roofing", "col": "work_email", "status": "done", "provider": "find_contact_info", "error": null}, {"company": "Suncoast Shingle Co", "col": "email_provider", "status": "done", "provider": "email_provider", "error": null}, {"company": "Suncoast Shingle Co", "col": "site_status", "status": "done", "provider": "website_check", "error": null}, {"company": "Suncoast Shingle Co", "col": "work_email", "status": "done", "provider": "email_permutations", "error": null}, {"company": "Palmetto Peak Roofs", "col": "email_provider", "status": "done", "provider": "email_provider", "error": null}, {"company": "Palmetto Peak Roofs", "col": "site_status", "status": "done", "provider": "website_check", "error": null}, {"company": "Palmetto Peak Roofs", "col": "work_email", "status": "no_result", "provider": null, "error": "Find contact info on site: no_result; Email permutations: failed validation"}, {"company": "Keystone Coastal Roofing", "col": "email_provider", "status": "error", "provider": "email_provider", "error": "DNS lookup failed: sample error, run it again"}]') m
    ON json_extract(m.value, '$.company') = json_extract(r.data, '$.company') AND json_extract(m.value, '$.col') = c.key;
